development:
  type: xmpp4r
  jid: sid_repo@infomine.dsv-gruppe.de
  password: CT.PDQQDr#VQSu,b.ISGsV6GPv$SDvTC
  host: infomine.dsv-gruppe.de
  port: 5223
  status: hello world
  ssl: true
  debug: true

test:
  type: mock

production:
  type: xmpp4r
  jid: sid_repo@infomine.dsv-gruppe.de
  password: CT.PDQQDr#VQSu,b.ISGsV6GPv$SDvTC
  host: infomine.dsv-gruppe.de
  port: 5223
  status: hello world
  ssl: true
  debug: true